### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by KangJiJi** [TeamCrazyPerformance/mozzi_front#4]
1. 프로젝트 목록페이지

2. 프로젝트 생성, 수정 페이지

3. 프로젝트 보기 페이지

4. 프로젝트 신청 멤버 보기(가입 승인, 거절 버튼)

5. 이슈 생성, 목록, 상세보기

등등 알아서

### Domain : project

1. 프로젝트 목록 ( / ) `GET` 
    **request**
    ```
    limit (query)
    page (query)
    ```
    **response**
    ```
    200
    {
    success : true,
    projects : [
     {
      projectId : {int},
      link : {string} (""/project/{projectId}""),
      name : {string},
      author : {string} (userName),
      date : {string}
     }
    ],
    page : {int},
    count : {int},
    total : {int}
    }
    ```

2. 프로젝트 생성 ( / ) `POST`
    **request**
    ```
    {
    name : {string},
    content : {string},
    isPublic : {bool}
    }
    ```
    **response**
    ```
    201
    {
    success : true
    }
    ```
    이름, 개요, 공개여부만 설정가능
    멤버, 개발스택 등의 정보는 수정에서 추가가능

3. 프로젝트 보기 ( /{projectId} ) `GET`
    **request**
    ```
    projectId (path)
    ```
    **response**
    ```
    200
    {
    success : true
    name : {string},
    content : {string},
    members : {string}
    }
    ```

4. 프로젝트 수정 ( /{projectId} ) `PUT`
    **request**
    ```
    projectId, 
    {
    name : {string},
    content : {string}, 
    stack : {string},
    isPublic : {bool}
    }
    ```
    **response**
    ```
    200
    {
    success : true
    }
    ```

5. 프로젝트 삭제 ( /{projectId} ) `DELETE`
    **request**
    ```
    projectId (path)
    ```
    **response**
    ```
    200
    {
    success : true
    }
    ```

6. 신청 멤버 보기 ( /join/{projectId} ) `GET`
    **request**
    ```
    projectId (path)
    userId (jwt)
    ```
    **response**
    ```
    200
    {
    success : true,
    users : [
     {
      userId : {int},
      link : {string} (""/user/{userId}""),
      userName : {string},
      stdNumber : {int},
     }
    ]
    }
    ```

7. 가입 승인 ( /{projectId}/approve/{userId} ) `PUT`
    **request**
    ```
    userId (path)
    ```
    **response**
    ```
    200
    {
    success : true
    }
    ```

8. 가입 거절 ( /{projectId}/reject/{userId} ) `PUT`
    **request**
    ```
    userId (path)
    ```
    **response**
    ```
    200
    {
    success : true
    }
    ```

9. 참여 ( /join/{projectId} ) `POST`
    **request**
    ```
    projectId (path),
    userId (jwt)
    ```
    **response**
    ```
    200
    {
    success : true
    }
    ```
    프로젝트 작성자 승인 필요

10. 탈퇴 ( /{projectId}/exit/{userId} ) `DELETE`
    **request**
    ```
    projectId (path)
    userId (jwt)
    ```
    **response**
    ```
    401 (GONE)
    ```
    넌 못지나간다

11. 이슈 보기 ( /{projectId}/issue ) `GET`
    **request**
    ```
    projectId (path)
    ```
    **response**
    ```
    200
    {
    success : true,
    issues : [
     {
      id : {int} (issueId),
      issuelink : {string} 
       (""/project/{projectId}/issue/{issueId}""),
      author : {int},
      authorName : {string},
      userlink : {string} (""/user/{userId}""),
      title : {string},
      date : {string}
     }
    ]
    }
    ```
    발생이슈에 관한 토론을 할 수 있음
    이슈
    - title, content로 이루어짐
    - 댓글(코멘트) 추가 가능
    - 코멘트는 content 하나로 이루어짐

    이슈 상세보기는 작성자, 제목, 시간만 나옴
    (상세 내용 및 댓글은 표시되지 않음)

12. 이슈 생성 ( /{projectId}/issue ) `POST`
    **request**
    ```
    projectId (path)
    {
    title : {string},
    content : {string}
    }
    ```
    **response**
    ```
    201
    {
    success : true
    }
    ```

13. 이슈 상세보기 ( /{projectId}/issue/{issueId} ) `GET`
    **request**
    ```
    projectId (path),
    issueId (path)
    ```
    **response**
    200
    {
    success : true,
    issue : {
     id : {int} (issueId),
     author : {int},
     authorName : {string},
     userlink : {string} (""/user/{userId}""),
     title : {string},
     content : {string}
    },
    comments : [
     {
      id : {int} (commentId),
      author : {int},
      authorName : {string},
      userlink : {string} (""/user/{userId}""),
      date : {string},
      content : {string}
     }
    ]
    }
    ```

14. 이슈 코멘트 ( /{projectId}/issue/{issueId} ) `POST`
    **request**
    ```
    projectId (path),
    issueId (path), 
    {
    content : {string}
    }
    ```
    **response**
    ```
    200
    {
    success : true
    }
    ```

15. 이슈 수정 ( /{projectId}/issue/{issueId} ) `PUT`
    **request**
    ```
    projectId (path),
    issueId (path), 
    {
    title : {string},
    content : {string},
    state : {string} (open | close)
    }
    ```
    **response**
    ```
    200
    {
    success : true
    }
    ```

16. 진행상황 ( /{projectId}/board ) `GET`
    **request**
    ```
    projectId (paht)
    ```
    **response**
    ```
    200
    {
    success : true,
    boards : [
     {
      id : {int},
      author : {int},
      name : {string} (author nickname),
      userlink : {string} (""/user/{userId}""),
      title : {string},
      content : {string}
      state : {string} (todo | progress | done),
     }
    ]
    }
    ```
    생성된 상황들 보기
    진행상황
    - todo, progress, done 의 상태를 가짐
    - 각각 title, content가 있음
    - 댓글 불가능
    - 작성자 닉네임 공개

17. 진행상황 (생성) ( /{projectId}/board ) `POST`
    **request**
    ```
    projectId (path),
    {
    title : {string},
    content : {string}
    }
    ```
    **response**
    ```
    201
    {
    success : true
    }
    ```
    기본 todo 로 생성됨

18. 진행상황 (옮기기) ( /{projectId}/board/{boradId} ) `PUT`
    **request**
    ```
    id (path), 
    {
    state : {string} (progress | done)
    }
    ```
    **response**
    ```
    200
    {
    success : true
    }
    ```

19. 진행상황 (삭제) ( /{projectId}/board/{boardId} ) `DELETE`
    **request**
    ```
    boardId (path)
    ```
    **request**
    ```
    200
    {
    success : true
    }
    ```

20. 검색 ( /search ) `GET`
    **request**
    ```
    {
    type : {string},
    content : {string}
    }
    ```
    **response**
    ```
    200
    {
    success : true
    }
    ```
    이름, 작성자 기준으로 검색

**Comment by Kwoo4357** [comment]
https://reactjs.org/docs/hooks-reference.html#useeffect
